### ISSUE TITLE
There is no sound in Plugins after 0.8.850 version

### ISSUE THREAD

**Issue by jauhenk** [Temasys/AdapterJS#109] opened 2015-09-03 09:14 UTC
Hello guys,
I found that there is no incoming sound of audio track in plugins after 0.8.850 version.
I tested chrome - ie, ie with 850 plugin - ie with 854. With 0.8.850 all is correct.
Could you please take a look?
Thanks!

**Comment by johache** [comment] 2015-09-03 10:01
Hi Eugene,
Did you update your AdapterJS to version 0.12.0 ?

**Comment by jauhenk** [comment] 2015-09-03 14:45
We have a custom solution based on earlier version - only IE part.
Could you please provide me with a major changes?

**Comment by jauhenk** [comment] 2015-09-03 14:48
Will use history better:) Will let you know the state.

**Comment by johache** [comment] 2015-09-04 02:02
The critical changes that you want to look for are in this commit: https://github.com/Temasys/AdapterJS/commit/df2de3fdeb3fcd1df7bfc410f2d5ac1a8a44f866

It looks like there is a lot of changes, but it's mainly indentation. The "real" changes are actually quite small.
What changes is
- <audio> tags are places by <object> tags as <video> tags were before
- the plugin expect a "tag" <param> to know what kind of tag it is replacing.

Link to the release notes : https://github.com/Temasys/AdapterJS/releases/tag/0.12.0

May I know what are the motivations leading you to make a custom integration instead of using AJS ?

**Comment by jauhenk** [comment] 2015-09-04 20:21
Thank you for your comments!
I tried today different manipulations with the attachMediaStream but still have issue.
When I have an audio call and turn on camera with microphone - sound disappears.
We just had already implemented polyfill for webrtc.

**Comment by jauhenk** [comment] 2015-09-07 15:29
I found that you have some strange logic with audio.enabled. When I have video to mute myself I still should use enableSoundTracks(false)

**Comment by mEkblom** [comment] 2015-10-19 13:38
Hi,

I'm experiencing exactly the same issue. Video plays without sound (which seems odd because video is running perfectly otherwise, just missing sound, and it worked with earlier versions of the plugin).

Could you please clarify your comment above? Does it solve the sound issue?

**Comment by johache** [comment] 2015-10-20 03:53
Hi,

EnableSoundTracks is a legacy implementation that is expected to be deprecated in the near future.
We cannot remove it at the moment as the current plugin still depends on it (which is actually a bug)
EnableSoundTracks will continue to be called from AdapterJS to ensure compatibility with older versions of the plugin.

I may have a found way of reproducing you issue.

Can you both do the following:
- provide us with your version of Windows, IE, the plugin and AJS if you use it.
- in the Windows sound preferences, select different audio output as default (speaker, headphones jack, virtual recorder, whatever), and try the test against this page : https://plugin.temasys.com.sg/demo/samples/web/content/peerconnection/states/

Also, several topic about it are popping (https://groups.google.com/forum/#!topic/temasys-discuss-webrtcplugin/Q0eiv70Ctxg) 
Can we try to centralise the discussion here :)

**Comment by mEkblom** [comment] 2015-10-20 07:33
I have managed to locate the issue.

Contrary to other WebRTC implementations the plugin has audio off by default (to have sound off by default on an audio element seems especially odd). This means that when connecting a stream the `AudioMediaTrack` *must be retrieved and set to enabled*. There is also a bug that if the `enabled` property of the AudioMediaTrack is set to `true` _before the object element is injected_, *it will be reset to false*. Really, the best solution in my opinion would be to automatically enable audio as other implementations do for consistency.

Also the muted property does not seem to be implemented (this would be needed if enableSoundTracks would be removed). I would suggest also adding a muted property to the object element in the same way that audio and video elements have.

I will provide more details in the discussion group thread.

**Comment by johache** [comment] 2015-10-21 03:24
I'm fairly confused by what you're telling me.

1 - Contrary to other WebRTC implementations the plugin has audio off by default (to have sound off by default on an audio element seems especially odd).
Are you talking about the DOM element or the AudioTrack ?
None of them should be off by default

2- This means that when connecting a stream the AudioMediaTrack must be retrieved and set to enabled
The AudioTrack is automatically set enabled when it has at least one renderer (AND if enableSoundTrack was called)
It is automatically disabled when it has no renderer.

3- There is also a bug that if the enabled property of the AudioMediaTrack is set to true before the object element is injected, it will be reset to false. 
Our documentation specifically states that you CANNOT call attachMediaStream before your <audio>/<video> tag is injected in the DOM.
https://temasys.atlassian.net/wiki/display/TWPP/How+to+integrate+the+Temasys+WebRTC+Plugin+into+your+website

4- Also the muted property does not seem to be implemented
That is correct, AudioTrack.muted is missing from the plugin at the moment.

**Comment by mEkblom** [comment] 2015-10-21 14:37
1. Talking about the [MediaStreamTrack] (http://w3c.github.io/mediacapture-main/#widl-MediaStreamTrack-enabled). The fact is that it is disabled, easily discovered by reading the property. And exactly, it shouldn't be. 

2. In that case it should be enabled as soon as it gets a renderer, otherwise it will always be disabled.

3. We are not calling `attachMediaStream`, as I said we don't use the adapter. What I can see from the adapter code and `attachMediaStream` the only difference is that `enableSoundTracks` is called before inserting the audio/video object element. Perhaps this is a requirement but I would expect `play()` or `pause()` to be possible to call at any time to stop or start rendering.

4. I really would suggest implementing the `muted` property but not on the MediaStreamTrack but on the object element like is for [audio/video elements](http://www.w3schools.com/tags/ref_av_dom.asp). That together with the `play` and `pause` methods would be a great improvement.

About 4, actually I noticed that setting `muted` to `true` did stop sound but reversely to `false` it had no effect (it didn't start sound again). What is worse, calling `enableSoundTracks` with `true` has no effect so there is no simple way to implement mute functionality. To reproduce this, just start audio or video, call `enableSoundTracks(false)` after audio started - sound will be muted as expected. Do `enableSoundTracks(true)` after this - nothing will happen.

**Comment by johache** [comment] 2015-10-22 06:47
1. We actually set this value to false by default because otherwise the MediaStreamTrack would just start playing before being attached to anything (I know it's not the case in Chrome, but it is for us)

2. Enabled when attached to a renderer: I agree with that.
At the moment, you still have to go through the enableSoundTracks step, but eventually, you won't

3. No AJS: ok, sorry to ask again, but then can you test against this demo : 
https://plugin.temasys.com.sg/demo/samples/web/content/peerconnection/states/
I need to make sure if the issue is specific to you installation or if it is with your app implementation.
If it's not too sensible, could you make available to us your app or a simple example for us to reproduce your issue ?
Play & pause contain a different logic. They let the specific renderer play or not play the stream. Playing a disabled stream will NOT render it.

4. <object>.muted is already implemented

5. I tested setting <object>.muted = true and = false (on the demo page I gave you earlier), and my sound is enabled and disabled as expected.

**Comment by mEkblom** [comment] 2015-10-22 14:31
1. About Chrome, audio starts as soon as the stream is set as source, the audio element does not even need to be inserted into the DOM.

3. I tested your link but it reports _getUserMedia error_ as soon as I click start. I did check it with https://plugin.temasys.com.sg/demo/samples/web/content/peerconnection/audio/index.html earlier and it worked as expected. I agree about play/pause but anyhow it would be great to have it implemented because it is a very simple way to start and stop audio/video.

5. `muted` worked but only to mute and not to unmute when I tried it in our app.

**Comment by johache** [comment] 2015-10-23 06:22
1. About Chrome, audio starts as soon as the stream is set as source, the audio element does not even need to be inserted into the DOM.
-> I understand that, but browsers won't detect a plugin element unless it is in the DOM.
This is a limitation of the NPAPI/ActiveX interface, nothing we can do about that.

2. I tested your link but it reports getUserMedia error as soon as I click start. I did check it with https://plugin.temasys.com.sg/demo/samples/web/content/peerconnection/audio/index.html earlier and it worked as expected.
-> Do you have a camera available ?
I agree about play/pause but anyhow it would be great to have it implemented because it is a very simple way to start and stop audio/video.
-> I understand what you say, and I agree that simplicity is great, but it shouldn't be at the expense of application logic and spec compliance.
I'll need to double check what's Chrome behaviour on this

3. muted worked but only to mute and not to unmute when I tried it in our app.
-> again, I don;t have this behaviour in my case. Do you have a code sample to reproduce the issue ?

**Comment by johache** [comment] 2016-03-15 06:05
Hey guys,

By bullet point:
1. NPAPI/ActiveX limitation
2. enableSoundTrack is now empty, I don't see any issue remaining
3. not reproduced

I am closing this issue as I don't see any extra work expected.

**Closed by johache** 2016-03-15 06:05 UTC
