### ISSUE TITLE
malformed constraints adapter-debug.js

### ISSUE THREAD

**Issue by transonly** [Temasys/AdapterJS#146] opened 2016-01-11 06:46 UTC
This is what i'm sending over to adapter-debug.js:
{"iceServers":[{"url":"stun:stun.l.google.com:19302"},{"url":"turn:turn.bistri.com:80","credential":"homeo","username":"homeo"}]}, 
{"mandatory":{"OfferToReceiveAudio":true,"OfferToReceiveVideo":true}}

What i get is:

Uncaught TypeError: Failed to construct 'RTCPeerConnection': Malformed constraints object.

**Comment by johache** [comment] 2016-01-11 08:19
Hi,

Which browser, which version ?

**Comment by transonly** [comment] 2016-01-11 10:20
chrome Versie 47.0.2526.106 m
Opera Version:	34.0.2036.25

**Comment by johache** [comment] 2016-01-12 06:20
I don't see anything wrong with this.
I made a quick try on my side and it seemed to work fine.
@letchoo any input here ?

**Comment by letchoo** [comment] 2016-01-12 07:15
Hi @johache, I do not have any issues with it.

I've tested with Chrome Version 47 and Opera Version 34.

**Comment by johache** [comment] 2016-01-14 02:28
Hi transonly,
We can't reproduce your issue, do you still have it on your end?
Do you have a live code that we could test against ?

**Comment by johache** [comment] 2016-03-15 05:53
Hi,
We cannot reproduce the issue here and nothing happened in this thread for the past 2 months.
I'm going to close this issue, if you think this is relevant, please re-open it.

**Closed by johache** 2016-03-15 05:53 UTC
