### ISSUE TITLE
MS Edge support

### ISSUE THREAD

**Issue by jvandereijk** [Temasys/AdapterJS#99] opened 2015-07-30 13:41 UTC
Hi,

Are there any plans for the Temasys adapterJs to support the new Microsoft Edge browser ?
According to https://blog.andyet.com/2015/06/25/webrtc-on-the-edge it is possible to use native WebRTC in Edge, but at the moment the plugin message still appears, but obviously fails to install, and the WebRTC componont will not work. 

Thanks

**Comment by johache** [comment] 2015-07-31 03:59
Yes. 
We didn't quite get to try Edge so far, but it is at the top of our todo list.

**Comment by agouaillard** [comment] 2015-07-31 10:39
microsoft edge only supports getusermedia, but not the peer connection and
the dat channel API.

On Fri, Jul 31, 2015 at 12:59 PM, Jacques-Olivier Haché <
notifications@github.com> wrote:

> Yes.
> We didn't quite get to try Edge so far, but it is at the top of our todo
> list.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/AdapterJS/issues/99#issuecomment-126560746>.
>



-- 
Alex. Gouaillard, PhD, PhD, MBA
------------------------------------------------------------------------------------
CTO - Temasys Communications, S'pore / Mountain View
President - CoSMo Software, Cambridge, MA
------------------------------------------------------------------------------------
sg.linkedin.com/agouaillard

   -

**Comment by bart-jansen** [comment] 2015-08-11 08:27
any estimate available for when the adapterJS plugin will be fully supported with IE Edge ?

**Comment by z0r1k** [comment] 2015-09-17 09:28
Didn't Edge suppose to be plugin free? At least no ActiveX/NPAPI? 
Also Edge is going to support ORTC and not WebRTC, so will AdapterJS start to support plugin free ORTC and convert it to WebRTC?

**Comment by bart-jansen** [comment] 2015-09-17 14:27
Is ORTC in MS Edge usable yet? i.e. has somebody managed to successfully communicate through a RTCPeerConnection-like way in MS Edge?

**Comment by z0r1k** [comment] 2015-09-17 14:28
ORTC is not yet released, right?

**Comment by agouaillard** [comment] 2015-09-18 00:34
no it's not, even though the base is there and made it s way out of the
internal builds:
https://twitter.com/MSEdgeDev/status/633702738019381248

It has also been reported that RTPSender and Receiver are there:
https://twitter.com/warrenjmcdonald/status/638213922630336512

but not full ORTC yet.

Rumor on the street says it's around the corner (a week).


On Thu, Sep 17, 2015 at 10:28 PM, Michael (Mykhailo) Lieibenson <
notifications@github.com> wrote:

> ORTC is not yet released, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/AdapterJS/issues/99#issuecomment-141103908>.
>



-- 
Alex. Gouaillard, PhD, PhD, MBA
------------------------------------------------------------------------------------
President - CoSMo Software Consulting, Singapore
------------------------------------------------------------------------------------
sg.linkedin.com/agouaillard

   -

**Comment by johache** [comment] 2015-09-18 02:16
Answering several questions that same up here:
- Edge does not support plugins. The Temasys WebRTC plugin does not and will not add support to WebRTC in Edge. No plugin ever will, it is not possible by design of Edge.
- Microsoft Edge already supports getUserMedia and is moving towards ORTC. All interfaces are not present yet, and AFAIK, it's not possible to start a connection yet.
- A good link to follow the status is : https://dev.modern.ie/platform/status. 
The two twitter accounts provided by Dr Gouaillard are also pretty useful. 
I would also recommend this conference on youtube - only valid at the publication date, obviously - https://www.youtube.com/watch?v=nQ_NgkpLyjw&index=13&list=PLNYkxOF6rcICT_h7pn39XpU4JkqOja3p- 
- Temasys is aligning with Google's version of AdapterJS - which, I think, Microsoft is actually contributing to -. We already released a version that support getUserMedia and attachMediaStream : https://github.com/Temasys/AdapterJS/releases/tag/0.12.0

**Comment by agouaillard** [comment] 2015-09-18 07:55
Wrong.

Edge will support plugin, but only through enterprise policies. there will
be a second binary that can be launched and that is IE compatible. The
reason why they still have support for plugin, even if it is just for the
entreprise, is simple: some microsoft products, including outlook still
depend on plugins. One will not be able to make that binary the default
browser, nor will one be able to launch it from command line. If your
clients are people connecting from home, forget about plugin. If your
client is an enterprise, their IT team should contact microsoft.

For more information, you can try to contact shijun sun, Senior Product
manager for the IE platform Team at microsoft. You can say I sent you.

Google version of Adapter.js has support from Edge's GetUsermedia that was
contributed by Philipp Hancke (fippo) from &yet. Microsoft is not, and will
not contribute to it.

I have personally not tested it, but my source is solid: ORTC should be out
anytime soon, and the (webrtc on ortc) shim is already written. There
should be no need for a plugin in newest versions of Edge/Windows, as far
as webrtc is concerned. The interoperability with other HTML5 features
(like <video>, web audio, ....) should also be much easier than with a
plugin.

On Fri, Sep 18, 2015 at 10:16 AM, Jacques-Olivier Haché <
notifications@github.com> wrote:

> Answering several questions that same up here:
>
>    - Edge does not support plugins. The Temasys WebRTC plugin does not
>    and will not add support to WebRTC in Edge. No plugin ever will, it is not
>    possible by design of Edge.
>    - Microsoft Edge already supports getUserMedia and is moving towards
>    ORTC. All interfaces are not present yet, and AFAIK, it's not possible to
>    start a connection yet.
>    - A good link to follow the status is :
>    https://dev.modern.ie/platform/status. The two twitter accounts
>    provided by Dr Gouaillard are also pretty useful. I would also recommend
>    this conference on youtube - only valid at the publication date, obviously
>    -
>    https://www.youtube.com/watch?v=nQ_NgkpLyjw&index=13&list=PLNYkxOF6rcICT_h7pn39XpU4JkqOja3p-
>    - Temasys is aligning with Google's version of AdapterJS - which, I
>    think, Microsoft is actually contributing to -. We already released a
>    version that support getUserMedia and attachMediaStream :
>    https://github.com/Temasys/AdapterJS/releases/tag/0.12.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/AdapterJS/issues/99#issuecomment-141309721>.
>



-- 
Alex. Gouaillard, PhD, PhD, MBA
------------------------------------------------------------------------------------
President - CoSMo Software Consulting, Singapore
------------------------------------------------------------------------------------
sg.linkedin.com/agouaillard

   -

**Comment by agouaillard** [comment] 2015-09-18 07:56
oh, and as for hookflash (the youtube video pointed to by JO), I would take
what they CEO said with a grain of salt. You might want to refer to the
part by Bernard A. from M.. He did not say it all, but what is said can be
taken to the bank.


On Fri, Sep 18, 2015 at 3:55 PM, Alexandre GOUAILLARD <agouaillard@gmail.com
> wrote:

> Wrong.
>
> Edge will support plugin, but only through enterprise policies. there will
> be a second binary that can be launched and that is IE compatible. The
> reason why they still have support for plugin, even if it is just for the
> entreprise, is simple: some microsoft products, including outlook still
> depend on plugins. One will not be able to make that binary the default
> browser, nor will one be able to launch it from command line. If your
> clients are people connecting from home, forget about plugin. If your
> client is an enterprise, their IT team should contact microsoft.
>
> For more information, you can try to contact shijun sun, Senior Product
> manager for the IE platform Team at microsoft. You can say I sent you.
>
> Google version of Adapter.js has support from Edge's GetUsermedia that was
> contributed by Philipp Hancke (fippo) from &yet. Microsoft is not, and will
> not contribute to it.
>
> I have personally not tested it, but my source is solid: ORTC should be
> out anytime soon, and the (webrtc on ortc) shim is already written. There
> should be no need for a plugin in newest versions of Edge/Windows, as far
> as webrtc is concerned. The interoperability with other HTML5 features
> (like <video>, web audio, ....) should also be much easier than with a
> plugin.
>
> On Fri, Sep 18, 2015 at 10:16 AM, Jacques-Olivier Haché <
> notifications@github.com> wrote:
>
>> Answering several questions that same up here:
>>
>>    - Edge does not support plugins. The Temasys WebRTC plugin does not
>>    and will not add support to WebRTC in Edge. No plugin ever will, it is not
>>    possible by design of Edge.
>>    - Microsoft Edge already supports getUserMedia and is moving towards
>>    ORTC. All interfaces are not present yet, and AFAIK, it's not possible to
>>    start a connection yet.
>>    - A good link to follow the status is :
>>    https://dev.modern.ie/platform/status. The two twitter accounts
>>    provided by Dr Gouaillard are also pretty useful. I would also recommend
>>    this conference on youtube - only valid at the publication date, obviously
>>    -
>>    https://www.youtube.com/watch?v=nQ_NgkpLyjw&index=13&list=PLNYkxOF6rcICT_h7pn39XpU4JkqOja3p-
>>    - Temasys is aligning with Google's version of AdapterJS - which, I
>>    think, Microsoft is actually contributing to -. We already released a
>>    version that support getUserMedia and attachMediaStream :
>>    https://github.com/Temasys/AdapterJS/releases/tag/0.12.0
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Temasys/AdapterJS/issues/99#issuecomment-141309721>.
>>
>
>
>
> --
> Alex. Gouaillard, PhD, PhD, MBA
>
> ------------------------------------------------------------------------------------
> President - CoSMo Software Consulting, Singapore
>
> ------------------------------------------------------------------------------------
> sg.linkedin.com/agouaillard
>
>    -
>
>


-- 
Alex. Gouaillard, PhD, PhD, MBA
------------------------------------------------------------------------------------
President - CoSMo Software Consulting, Singapore
------------------------------------------------------------------------------------
sg.linkedin.com/agouaillard

   -

**Comment by johache** [comment] 2015-09-18 08:22
My current understanding is as follow:
- Edge does not and will not support ActiveX plugins
- The second browser installed in Windows 10 is IE 11. It is a legacy browser and will only be available through IT policies. 
- As you said, this is to provide support for corporate products and even for Microsoft's own products.

link : http://www.computerworld.com/article/2920892/web-browsers/microsoft-nixes-activex-add-on-technology-in-new-edge-browser.html
link : http://www.windowscentral.com/microsoft-confirms-its-new-edge-browser-wont-support-its-silverlight-player

Regarding support in adapter.js, my bad, I didn't check, the first commit is there : https://github.com/webrtc/adapter/commit/3374f5d63f82268dffd26aad15ed3d5f8f0534d1

**Comment by agouaillard** [comment] 2015-09-19 03:37
Alright,

I can speak publicly about it now, since the cat is out of the bag.

Microsoft insiders builds now have full support for ORTC.
http://blogs.windows.com/msedgedev/2015/09/18/ortc-api-is-now-available-in-microsoft-edge/
You will note that the main author of the blog post is shijun sun I had
pointed you to previously.

test here:
https://dev.modern.ie/testdrive/demos/ortcdemo/

The important vendors (and consultants) in the ecosystem had access to it
for quite some time now. JS SDKs, mobile SDKs, and plugins supporting ORTC
are ready and should be made public soon now.

See e.g. the microsoft twilio demo:
https://dev.modern.ie/testdrive/demos/twilioortc/

With their webrtc-ortc-shim:
https://github.com/twilio/ortc-adapter



On Fri, Sep 18, 2015 at 4:22 PM, Jacques-Olivier Haché <
notifications@github.com> wrote:

> My current understanding is as follow:
>
>    - Edge does not and will not support ActiveX plugins
>    - The second browser installed in Windows 10 is IE 11. It is a legacy
>    browser and will only be available through IT policies.
>    - As you said, this is to provide support for corporate products and
>    even for Microsoft's own products.
>
> link :
> http://www.computerworld.com/article/2920892/web-browsers/microsoft-nixes-activex-add-on-technology-in-new-edge-browser.html
> link :
> http://www.windowscentral.com/microsoft-confirms-its-new-edge-browser-wont-support-its-silverlight-player
>
> Regarding support in adapter.js, my bad, I didn't check, the first commit
> is there : webrtc/adapter@3374f5d
> <https://github.com/webrtc/adapter/commit/3374f5d63f82268dffd26aad15ed3d5f8f0534d1>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/AdapterJS/issues/99#issuecomment-141379471>.
>



-- 
Alex. Gouaillard, PhD, PhD, MBA
------------------------------------------------------------------------------------
President - CoSMo Software Consulting, Singapore
------------------------------------------------------------------------------------
sg.linkedin.com/agouaillard

   -

**Comment by johache** [comment] 2016-03-15 06:07
Edge support started with 0.13.0 and updated today with 0.13.1 (RTCPeerConnection, ...)
Closing this issue.

**Closed by johache** 2016-03-15 06:07 UTC
