### ISSUE TITLE
Free camera resource on MedaiStream.stop()

### ISSUE THREAD

**Issue by z0r1k** [Temasys/AdapterJS#79] opened 2015-05-15 09:46 UTC
Calling MediaStream.stop() doesn't free camera lock since usage indicator (LED) is still on.

**Comment by serrynaimo** [comment] 2015-06-09 02:28
@johache Is this still a problem? Can't reproduce

**Comment by johache** [comment] 2015-06-09 02:33
Cannot reproduce either.
z0r1k, can you check this:
https://plugin.temasys.com.sg/demo/samples/web/content/getusermedia/gum/index.html
It's a VERY simple example, you can call stream.stop() from the console, it will turn off the camera indicator.

You issue might be coming from a connection with a peer.
The plugin will not stop the camera if you are sharing it with someone.
One this example: https://plugin.temasys.com.sg/demo/samples/web/content/peerconnection/states/index.html
You have to call localstream.stop() and pc1.close() to turn off the camera.

**Comment by z0r1k** [comment] 2015-06-10 15:03
Ah, OK, but this doesn't really help since my use-case is:

I establish peer connection with data channel for chat and they when someone wants to make a call I call  GUM to get audio and add it to peer connection.
Once someone wants to share his camera I do the same for video.

Obviously since temasys plugin doesn't support streamRemove method I have to call stop on stream itself. 
I cannot close peer connection in this case since audio and chat still running and if someone wants to share his camera again I just renegotiate, but in this case resource is still blocked, right?

**Comment by johache** [comment] 2015-06-11 09:53
Yes, I see the issue.
I don't have a magic solution as it is.
I think the best solution is to wait for us to implement removeStream.
You are not the first one to come with this issue, we will get to it asap, but we have a big pile of things to do for the plugin...

**Comment by johache** [comment] 2015-07-30 07:05
Given that remove stream was released in the latest public version, I am closing this issue.
Re-open it if you think it is relevant.

**Closed by johache** 2015-07-30 07:05 UTC

**Comment by santinoDu** [comment] 2019-09-06 09:44
> Cannot reproduce either.
> z0r1k, can you check this:
> https://plugin.temasys.com.sg/demo/samples/web/content/getusermedia/gum/index.html
> It's a VERY simple example, you can call stream.stop() from the console, it will turn off the camera indicator.
> 
> You issue might be coming from a connection with a peer.
> The plugin will not stop the camera if you are sharing it with someone.
> One this example: https://plugin.temasys.com.sg/demo/samples/web/content/peerconnection/states/index.html
> You have to call localstream.stop() and pc1.close() to turn off the camera.

@johache hi，this two demo page are 404 now. I have tried stop, can't work, what is the 'pc1' has a 'close' method?
