### ISSUE TITLE
black stream from IE (edge)

### ISSUE THREAD

**Issue by fix2015** [Temasys/AdapterJS#278] opened 2017-06-28 08:17 UTC
Hey guys, i have some trouble, when i use your product and try connect ie with chrome on diferent computer it send me stream with black screen, i have no error in console nothing just black screen from interlocutor. Do you have bugs like this?

**Comment by letchoo** [comment] 2017-06-28 08:59
Duplicate of [SkylinkJS #289](https://github.com/Temasys/SkylinkJS/issues/289).

**Closed by letchoo** 2017-06-28 08:59 UTC
