### ISSUE TITLE
Issue when app hosted in tomcat

### ISSUE THREAD

**Issue by teo89** [Temasys/AdapterJS#130] opened 2015-10-14 09:26 UTC
Hello,
I am trying to make examples Temasys/Google-WebRTC-Samples to run with tomcat. But IE fails in these two lines of adapter.js
frag.width = width;
frag.height = height; 
with error "invalid argument". Any ideas why there is these issue?

**Comment by johache** [comment] 2015-10-15 03:10
Hi,
This should not happen. The plugin is not dependent on any backend, therefore whatever server system you use (here, Tomcat) should be irrelevant.

Can you be more specific about what version of Windows, IE, the plugin and Adapter.js you use ?

Also, there are a lot of examples in Temasys/Google-WebRTC-Samples. Which ones in particular are you using ?

**Comment by teo89** [comment] 2015-10-15 08:36
I am using adapter.js from //cdn.temasys.com.sg/adapterjs/0.12.x/adapter.min.js but also file from https://github.com/Temasys/AdapterJS/tree/master/publish has the same issue
and i am running Google-WebRTC-Samples/samples/web/content/getusermedia/gum and 
Google-WebRTC-Samples/samples/web/content/peerconnection/munge-sdp.
I am in Windows 8 and IE 11 and Temasys version 0.8.854.

**Comment by teo89** [comment] 2015-10-20 10:02
Is nothing new about that issue?

**Comment by johache** [comment] 2015-10-21 04:04
I am not capable of reproducing your issue.
I am not running my tests on a tomcat server, but that should be irrelevant.

**Comment by johache** [comment] 2016-03-15 06:32
Hi,

Since we haven't reproduced the issue and there is not activity on the ticket, I'm going to close it.
Feel free to re-open should it be relevant.

**Closed by johache** 2016-03-15 06:32 UTC
