### ISSUE TITLE
setRemoteDescription issue

### ISSUE THREAD

**Issue by clusterberries** [Temasys/AdapterJS#126] opened 2015-10-01 13:15 UTC
Hello everyone,

A problem occurred in the method setRemoteDescription, when I try to set connection from Chrome 46 beta. The error is "SessionDescription is NULL". But there are no differences in session description object except in the media line: Chrome 45 sends "RTP/SAVPF" protocol, but Chrome 46 sends "UDP/TLS/RTP/SAVPF" protocol. If I try to change this manually it certainly does not work.
Connection between Chrome 46 and Firefox is established without any issues.

Thanks.

**Comment by jauhenk** [comment] 2015-10-05 08:49
Hey, we have the same issue.
Could you please take a look?

**Comment by johache** [comment] 2015-10-06 03:35
Hi guys,
Thanks for the feedback. I tested a reproduced this issue.
- The issue only happens when chrome 46 sends the offer, not the answer. That means that by changing the side of the call, you can bypass it.
- As pointed by clusterberries, the issue is in the offer parsing in the plugin.

We will need to spend some time on it to exactly figure it out and fix it, but it's a very high priority. 
We'll do our best to fix it before Chrome 46 is released as stable (which should be early November if I count right)

**Comment by z0r1k** [comment] 2015-10-07 12:29
In my opinion it might be caused by old WebRTC version which could be used by temasys plugin.
When you create an offer you can do something like ```offer.sdp = offer.sdp.replace(/UDP\/TLS\//g, "");``` which could fix Chrome to Temasys plugin communication issue.

**Comment by johache** [comment] 2015-10-08 02:36
Hi,
We made a quick fix that seems to work fine with Chrome 46.
However we would rather find a better, long term solution to this issue.

If we get to make it before Chrome 46 is released, great, otherwise we will release this quick fix.
The next version of Chrome should come on the first days of November. We will release a solution about 10 days before that to ensure continuity.

**Comment by jauhenk** [comment] 2015-10-09 09:07
Google released Chrome v46:)

**Comment by johache** [comment] 2015-10-09 09:12
Hum, my colleague's computer and this website say they didn't:
https://www.chromium.org/developers/calendar

When I say released, I mean in the *stable* channel.

**Comment by jauhenk** [comment] 2015-10-09 09:14
Looks like I should turn off auto update.
![clip2net_151009121345](https://cloud.githubusercontent.com/assets/8901848/10390129/4adf6fd2-6e7f-11e5-99a8-e1a483da5239.jpg)

**Comment by johache** [comment] 2015-10-09 10:03
Well, this is confusing...
None of our computers on stable channel got updated and I don't see any signe of update on Google's website.

**Comment by z0r1k** [comment] 2015-10-09 10:28
@jauhenk I guess you are on beta channel ;)

**Comment by soulhunter1987** [comment] 2015-10-18 06:40
OSX Google Chrome Version 46.0.2490.71 (64-bit). Got it within last few days on stable channel.

**Comment by johache** [comment] 2015-10-19 07:32
Hi all, 
We just released a version that should fix this issue for everyone.
See here for the announcement: https://groups.google.com/forum/#!topic/temasys-discuss-webrtcplugin/YMtpoOKCToQ
And here for the plugin portal : https://temasys.atlassian.net/wiki/display/TWPP/WebRTC+Plugins.

I am closing this issue since it should now work.

**Closed by johache** 2015-10-19 07:32 UTC
